name: check

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    tests:
        strategy:
            matrix:
                os: [ ubuntu-latest ]
                gradle-properties-version: [ 213, 221, 222, 223 ]

        runs-on: ${{ matrix.os }}
        env:
            ORG_GRADLE_PROJECT_shortPlatformVersion: ${{ matrix.gradle-properties-version }}

        steps:
            -   uses: actions/checkout@v2

            -   name: Set up JDK 17
                uses: actions/setup-java@v2
                with:
                    java-version: 17
                    distribution: 'zulu'

            -   name: Verify Plugin Configuration
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: "verifyPluginConfiguration"

            -   name: Build
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: "assemble testClasses -Pkotlin.incremental=false --no-daemon --stacktrace"

            -   name: Check
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: "check -Pkotlin.incremental=false --no-daemon --stacktrace"

            -   name: Verify plugin
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: "runPluginVerifier"
