name: check

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    tests:
        strategy:
            matrix:
                os: [ ubuntu-latest ]
                gradle-properties-version: [ 221, 222, 223 ]

        runs-on: ${{ matrix.os }}
        env:
            ORG_GRADLE_PROJECT_shortPlatformVersion: ${{ matrix.gradle-properties-version }}

        steps:
            -   uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    distribution: 'zulu'
                    java-version: 17

            -   name: Setup Gradle and dependencies
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: ":resolveDependencies -Pkotlin.incremental=false --no-daemon"
                    gradle-home-cache-excludes: |
                        caches/modules-2/files-2.1/com.jetbrains.intellij.idea
                        caches/modules-2/files-2.1/com.jetbrains.intellij.clion

            -   name: Verify Plugin Configuration
                run: ./gradlew verifyPluginConfiguration

            -   name: Build
                run: "./gradlew assemble testClasses -Pkotlin.incremental=false --no-daemon --stacktrace"

            -   name: Check
                run: "./gradlew check -Pkotlin.incremental=false --no-daemon --stacktrace"

            -   name: Verify plugin
                run: "./gradlew runPluginVerifier"
